CXXFLAGS+= -Wall
main: ${SRC}/main.torgiren.cpp ${BIN}/gameengine.o ${BIN}/planet.o
	${CXX} $^ -o ${TMP}/main.torgiren ${CXXFLAGS}
${BIN}/gameengine.o: ${SRC}/gameengine.cpp ${INCLUDE}/gameengine.h
	${CXX} -c ${SRC}/gameengine.cpp -o $@ ${CXXFLAGS}
${BIN}/planet.o: ${SRC}/planet.cpp ${INCLUDE}/planet.h
	${CXX} -c ${SRC}/planet.cpp -o $@ ${CXXFLAGS}

